export const transactions = [
  {
    id: "1",
    type: "Sent",
    amount: 1200,
    date: "2026-01-16",
    reference: "TXN001",
    isCredit: false,
  },
  {
    id: "2",
    type: "Received",
    amount: 5000,
    date: "2026-01-15",
    reference: "TXN001",
    isCredit: true,
  },
  {
    id: "3",
    type: "Bill Payment",
    amount: 750,
    date: "2026-01-14",
    reference: "TXN001",
    isCredit: false,
  },
  {
    id: "4",
    type: "Received",
    amount: 2300,
    date: "2026-01-13",
    reference: "TXN001",
    isCredit: true,
  },
  {
    id: "5",
    type: "Sent",
    amount: 900,
    date: "2026-01-12",
    reference: "TXN001",
    isCredit: false,
  },
  {
    id: "6",
    type: "Received",
    amount: 1200,
    date: "2026-01-11",
    reference: "TXN001",
    isCredit: true,
  },
  {
    id: "7",
    type: "Bill Payment",
    amount: 450,
    date: "2026-01-10",
    reference: "TXN001",
    isCredit: false,
  },
  {
    id: "8",
    type: "Sent",
    amount: 1500,
    date: "2026-01-09",
    reference: "TXN001",
    isCredit: false,
  },
  {
    id: "9",
    type: "Received",
    amount: 3400,
    date: "2026-01-08",
    reference: "TXN001",
    isCredit: true,
  },
  {
    id: "10",
    type: "Bill Payment",
    amount: 600,
    date: "2026-01-07",
    reference: "TXN001",
    isCredit: false,
  },
  {
    id: "11",
    type: "Sent",
    amount: 2000,
    date: "2026-01-06",
    reference: "TXN001",
    isCredit: false,
  },
  {
    id: "12",
    type: "Received",
    amount: 1800,
    date: "2026-01-05",
    reference: "TXN001",
    isCredit: true,
  },
  {
    id: "13",
    type: "Bill Payment",
    amount: 1200,
    date: "2026-01-04",
    reference: "TXN001",
    isCredit: false,
  },
  {
    id: "14",
    type: "Sent",
    amount: 700,
    date: "2026-01-03",
    reference: "TXN001",
    isCredit: false,
  },
  {
    id: "15",
    type: "Received",
    amount: 2500,
    date: "2026-01-02",
    reference: "TXN001",
    isCredit: true,
  },
  {
    id: "16",
    type: "Bill Payment",
    amount: 950,
    date: "2026-01-01",
    reference: "TXN001",
    isCredit: false,
  },
  {
    id: "17",
    type: "Sent",
    amount: 1300,
    date: "2025-12-31",
    reference: "TXN001",
    isCredit: false,
  },
  {
    id: "18",
    type: "Received",
    amount: 4100,
    date: "2025-12-30",
    reference: "TXN001",
    isCredit: true,
  },
  {
    id: "19",
    type: "Bill Payment",
    amount: 800,
    date: "2025-12-29",
    reference: "TXN001",
    isCredit: false,
  },
  {
    id: "20",
    type: "Sent",
    amount: 1100,
    date: "2025-12-28",
    reference: "TXN001",
    isCredit: false,
  },
];

export const NETWORKS = [
  { key: "mtn", name: "MTN", image: require("@/assets/network/MTN.png") },
  { key: "airtel", name: "Airtel", image: require("@/assets/network/airtel.png")  },
  { key: "glo", name: "GLO", image: require("@/assets/network/glo.png")  },
  { key: "9mobile", name: "9Mobile", image: require("@/assets/network/9mobile.png")  },
];

type Bundle = {
  bundle: number;
  size: string;
  duration: string;
  amount: number;
  title: string;
  category: string;
  addons?: string;
}; 


export const mtn_bundles: Bundle[] = [
  // DAILY / HOT
  {
    bundle: 75,
    size: "75MB",
    duration: "1 Day",
    amount: 75,
    title: "MTN Daily 75MB",
    category: "Daily",
    addons: "50MB Bonus",
  },
  {
    bundle: 110,
    size: "110MB",
    duration: "1 Day",
    amount: 100,
    title: "MTN Daily 110MB",
    category: "Daily",
    addons: "100MB Social",
  },
  {
    bundle: 230,
    size: "230MB",
    duration: "1 Day",
    amount: 200,
    title: "MTN Daily 230MB",
    category: "Daily",
    addons: "500MB Night",
  },
  {
    bundle: 1000,
    size: "1GB",
    duration: "1 Day",
    amount: 500,
    title: "MTN Daily 1GB",
    category: "Daily",
    addons: "1GB Night + 100MB YouTube",
  },
  {
    bundle: 2500,
    size: "2.5GB",
    duration: "1 Day",
    amount: 750,
    title: "MTN Daily 2.5GB HOT",
    category: "HOT",
    addons: "500MB YouTube + 500MB Instagram",
  },
  {
    bundle: 3000,
    size: "3GB",
    duration: "1 Day",
    amount: 1000,
    title: "MTN Daily 3GB HOT",
    category: "HOT",
    addons: "1GB Social + 500MB Night",
  },
  {
    bundle: 4000,
    size: "4GB",
    duration: "1 Day",
    amount: 1200,
    title: "MTN Daily 4GB HOT",
    category: "HOT",
    addons: "2GB Night",
  },

  // WEEKLY
  {
    bundle: 1200,
    size: "1.2GB",
    duration: "7 Days",
    amount: 700,
    title: "MTN Weekly 1.2GB",
    category: "Weekly",
    addons: "500MB YouTube",
  },
  {
    bundle: 1500,
    size: "1.5GB",
    duration: "7 Days",
    amount: 1000,
    title: "MTN Weekly 1.5GB",
    category: "Weekly",
    addons: "500MB Night",
  },
  {
    bundle: 3500,
    size: "11GB",
    duration: "7 Days",
    amount: 3500,
    title: "MTN Weekly 11GB",
    category: "Weekly",
    addons: "5GB Social",
  },

  // MONTHLY
  {
    bundle: 1500,
    size: "2GB",
    duration: "30 Days",
    amount: 1500,
    title: "MTN Monthly 2GB",
    category: "Monthly",
    addons: "500MB Night",
  },
  {
    bundle: 2500,
    size: "3.5GB",
    duration: "30 Days",
    amount: 2500,
    title: "MTN Monthly 3.5GB",
    category: "Monthly",
    addons: "1GB YouTube",
  },
  {
    bundle: 4500,
    size: "10GB",
    duration: "30 Days",
    amount: 4500,
    title: "MTN Monthly 10GB",
    category: "Monthly",
    addons: "2GB Night + 500MB Social",
  },
  {
    bundle: 6500,
    size: "12.5GB",
    duration: "30 Days",
    amount: 5500,
    title: "MTN Monthly 12.5GB",
    category: "Monthly",
    addons: "3GB Social",
  },
  {
    bundle: 9000,
    size: "25GB",
    duration: "30 Days",
    amount: 9000,
    title: "MTN Monthly 25GB",
    category: "Monthly",
    addons: "5GB YouTube + 5GB Night",
  },

  // 3 MONTHS +
  {
    bundle: 25000,
    size: "90GB",
    duration: "90 Days",
    amount: 25000,
    title: "MTN 3 Months 90GB",
    category: "3 Months+",
    addons: "10GB Social",
  },
  {
    bundle: 50000,
    size: "200GB",
    duration: "90 Days",
    amount: 50000,
    title: "MTN 3 Months 200GB",
    category: "3 Months+",
    addons: "20GB Night + 10GB Social",
  },
];


export const airtel_bundles: Bundle[] = [
  // Airtel bundles
  {
    bundle: 75,
    size: "75MB",
    duration: "1 Day",
    amount: 75,
    title: "Airtel Daily 75MB",
    category: "Daily",
  },
  {
    bundle: 100,
    size: "100MB",
    duration: "1 Day",
    amount: 100,
    title: "Airtel Daily 100MB",
    category: "Daily",
  },
  {
    bundle: 200,
    size: "200MB",
    duration: "2 Days",
    amount: 200,
    title: "Airtel 2‑Day 200MB",
    category: "Daily",
  },
  {
    bundle: 300,
    size: "300MB",
    duration: "2 Days",
    amount: 300,
    title: "Airtel 2‑Day 300MB",
    category: "Daily",
  },

  {
    bundle: 1000,
    size: "1.5GB + bonuses",
    duration: "7 Days",
    amount: 1000,
    title: "Airtel Weekly 1.5GB",
    category: "Weekly",
  },
  {
    bundle: 1500,
    size: "3.5GB + bonuses",
    duration: "7 Days",
    amount: 1500,
    title: "Airtel Weekly 3.5GB",
    category: "Weekly",
  },
  {
    bundle: 2500,
    size: "6GB + bonuses",
    duration: "7 Days",
    amount: 2500,
    title: "Airtel Weekly 6GB",
    category: "Weekly",
  },

  {
    bundle: 1500,
    size: "2GB",
    duration: "30 Days",
    amount: 1500,
    title: "Airtel Monthly 2GB",
    category: "Monthly",
  },
  {
    bundle: 2000,
    size: "3GB",
    duration: "30 Days",
    amount: 2000,
    title: "Airtel Monthly 3GB",
    category: "Monthly",
  },
  {
    bundle: 3000,
    size: "8GB",
    duration: "30 Days",
    amount: 3000,
    title: "Airtel Monthly 8GB",
    category: "Monthly",
  },
  {
    bundle: 5000,
    size: "13GB",
    duration: "30 Days",
    amount: 5000,
    title: "Airtel Monthly 13GB",
    category: "Monthly",
  },
  {
    bundle: 8000,
    size: "21GB",
    duration: "30 Days",
    amount: 8000,
    title: "Airtel Monthly 21GB",
    category: "Monthly",
  },

  {
    bundle: 50000,
    size: "300GB",
    duration: "90 Days",
    amount: 50000,
    title: "Airtel 3 Months 300GB",
    category: "3 Months+",
  },
];

export const glo_bundles: Bundle[] = [
  // Glo bundles
  {
    bundle: 45,
    size: "45MB",
    duration: "1 Day",
    amount: 50,
    title: "Glo Daily 45MB",
    category: "Daily",
  },
  {
    bundle: 105,
    size: "105MB",
    duration: "1 Day",
    amount: 100,
    title: "Glo Daily 105MB",
    category: "Daily",
  },
  {
    bundle: 235,
    size: "235MB + Night",
    duration: "1 Day",
    amount: 200,
    title: "Glo Daily 235MB + Night",
    category: "Daily",
  },
  {
    bundle: 500,
    size: "1.5GB + Night",
    duration: "1 Day",
    amount: 500,
    title: "Glo Daily 1.5GB + Night",
    category: "Daily",
  },

  {
    bundle: 1500,
    size: "3.5GB + 2GB Night",
    duration: "7 Days",
    amount: 1500,
    title: "Glo Weekly 3.5GB",
    category: "Weekly",
  },
  {
    bundle: 2000,
    size: "8.5GB + 2.5GB Night",
    duration: "7 Days",
    amount: 2000,
    title: "Glo Weekly 8.5GB",
    category: "Weekly",
  },

  {
    bundle: 1000,
    size: "2.6GB + Night",
    duration: "30 Days",
    amount: 1000,
    title: "Glo Monthly 2.6GB",
    category: "Monthly",
  },
  {
    bundle: 2500,
    size: "7.25GB + Night",
    duration: "30 Days",
    amount: 2500,
    title: "Glo Monthly 7.25GB",
    category: "Monthly",
  },
  {
    bundle: 5000,
    size: "16GB + Night",
    duration: "30 Days",
    amount: 5000,
    title: "Glo Monthly 16GB",
    category: "Monthly",
  },

  {
    bundle: 50000,
    size: "310GB",
    duration: "60 Days",
    amount: 50000,
    title: "Glo 60 Days 310GB",
    category: "3 Months+",
  },
];

export const tmobile_bundles: Bundle[] = [
  // 9mobile bundles
  {
    bundle: 50,
    size: "50MB",
    duration: "1 Day",
    amount: 50,
    title: "9mobile Daily 50MB",
    category: "Daily",
  },
  {
    bundle: 100,
    size: "100MB + Social",
    duration: "1 Day",
    amount: 100,
    title: "9mobile Daily Social 100MB",
    category: "Daily",
  },
  {
    bundle: 300,
    size: "1GB + Social",
    duration: "1 Day",
    amount: 300,
    title: "9mobile Daily 1GB + Social",
    category: "Daily",
  },
  {
    bundle: 500,
    size: "2GB + Social",
    duration: "3 Days",
    amount: 500,
    title: "9mobile 3 Days 2GB + Social",
    category: "Weekly",
  },

  {
    bundle: 1500,
    size: "7GB + 100MB Social",
    duration: "7 Days",
    amount: 1500,
    title: "9mobile Weekly 7GB + Social",
    category: "Weekly",
  },

  {
    bundle: 1000,
    size: "2GB + 2GB Night",
    duration: "30 Days",
    amount: 1000,
    title: "9mobile Monthly 2GB + Night",
    category: "Monthly",
  },
  {
    bundle: 3000,
    size: "10GB + Night",
    duration: "30 Days",
    amount: 3000,
    title: "9mobile Monthly 10GB + Night",
    category: "Monthly",
  },

  {
    bundle: 25000,
    size: "75GB",
    duration: "90 Days",
    amount: 25000,
    title: "9mobile 3 Months 75GB",
    category: "3 Months+",
  },
];
